<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SampleArtisanAndCollectionSeeder extends Seeder
{
    public function run(): void
    {
        // Prevent duplicate seeding if data already exists
        if (DB::table('collections')->count() > 0 || DB::table('artisans')->count() > 0) {
            return;
        }

        // Check if categories exist
        $categories = DB::table('categories')->pluck('id', 'slug')->toArray();
        if (empty($categories)) {
            $this->call(CategorySeeder::class);
            $categories = DB::table('categories')->pluck('id', 'slug')->toArray();
        }

        // Insert Artisans
        $artisanIds = [];
        
        $artisans = [
            [
                'name' => 'Nuradi',
                'photo_url' => null,
                'years_active' => '25',
                'specialty' => 'Kendi & Gentong (Gerabah Nuradi)',
                'story' => 'Pak Nuradi adalah salah satu pengrajin senior di Sitiwinangun yang fokus pada pembuatan kendi air tradisional dan gentong tanah liat.',
                'quote' => 'Setiap putaran tanah adalah bentuk dedikasi menjaga budaya leluhur.',
                'address' => 'Blok Pejaten, Desa Sitiwinangun',
                'phone' => '085213635533',
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Amini',
                'photo_url' => null,
                'years_active' => '30',
                'specialty' => 'Peralatan Masak (Gerabah Amini)',
                'story' => 'Ibu Amini memproduksi aneka gerabah kebutuhan dapur tradisional dengan ketekunan tinggi.',
                'quote' => 'Gerabah membawa rasa masakan yang lebih alami dan sehat.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '087729012085',
                'is_featured' => false,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kadmiya',
                'photo_url' => null,
                'years_active' => '15',
                'specialty' => 'Souvenir & Celengan (Kadmiya Craft)',
                'story' => 'Ibu Kadmiya mengkhususkan diri pada pembuatan kerajinan gerabah dekoratif berskala kecil dan souvenir.',
                'quote' => 'Bentuk kecil gerabah membawa kebahagiaan bagi anak-anak yang menabung.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '081320510521',
                'is_featured' => false,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maena',
                'photo_url' => null,
                'years_active' => '20',
                'specialty' => 'Peralatan Dapur',
                'story' => 'Ibu Maena membuat bermacam peralatan dapur tradisional berbahan tanah liat lokal.',
                'quote' => 'Menjaga tradisi lewat alat dapur sehari-hari.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '0895613976264',
                'is_featured' => false,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Miskadna',
                'photo_url' => null,
                'years_active' => '20',
                'specialty' => 'Kendi & Wadah',
                'story' => 'Pak Miskadna terampil dalam membentuk kendi tradisional dengan metode throwing.',
                'quote' => 'Tanah liat ini dibentuk dengan kesabaran agar bermanfaat bagi sesama.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '08980403556',
                'is_featured' => false,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marini',
                'photo_url' => null,
                'years_active' => '18',
                'specialty' => 'Vas & Pot (Dhijah)',
                'story' => 'Ibu Marini mengelola usaha Dhijah (Oma Getak) yang fokus pada produk vas bunga dan pot tanaman.',
                'quote' => 'Tanah liat memberikan kehangatan alami untuk setiap sudut hunian.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '081324009996',
                'is_featured' => true,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eka Budiatno',
                'photo_url' => null,
                'years_active' => '12',
                'specialty' => 'Benda Dekoratif',
                'story' => 'Kang Eka adalah generasi muda yang giat berinovasi membuat bentuk gerabah hias.',
                'quote' => 'Inovasi bentuk memperluas jangkauan keindahan gerabah kami.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '085224721110',
                'is_featured' => false,
                'sort_order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Si\'a',
                'photo_url' => null,
                'years_active' => '25',
                'specialty' => 'Celengan & Souvenir',
                'story' => 'Ibu Si\'a setia memproduksi aneka celengan karakter hewan tradisional dari tanah liat.',
                'quote' => 'Menabung adalah kebiasaan baik, celengan gerabah adalah pelindungnya.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '081324009996',
                'is_featured' => false,
                'sort_order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nurjaji',
                'photo_url' => null,
                'years_active' => '10',
                'specialty' => 'Kriya Modern (Apik Crap)',
                'story' => 'Kang Nurjaji mendirikan Apik Crap, memadukan seni gerabah lokal dengan selera minimalis modern.',
                'quote' => 'Seni tradisional tidak lekang oleh waktu jika dipadukan dengan ide-ide baru.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '083837907546',
                'is_featured' => true,
                'sort_order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tarsina',
                'photo_url' => null,
                'years_active' => '30',
                'specialty' => 'Peralatan Tradisional (Caplek Kulon)',
                'story' => 'Ibu Tarsina memproduksi gerabah di kawasan Caplek Kulon dengan mempertahankan cara-cara leluhur.',
                'quote' => 'Pekerjaan ini melekat di hati saya sejak muda.',
                'address' => 'Blok Caplek Kulon, Desa Sitiwinangun',
                'phone' => '081324009996',
                'is_featured' => false,
                'sort_order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rumsiti',
                'photo_url' => null,
                'years_active' => '22',
                'specialty' => 'Wajan & Cobek (Caplek Kidul)',
                'story' => 'Ibu Rumsiti membuat wajan dan cobek tanah liat di Caplek Kidul.',
                'quote' => 'Mengolah adonan tanah liat menjadi alat masak andalan dapur.',
                'address' => 'Blok Caplek Kidul, Desa Sitiwinangun',
                'phone' => '081324009996',
                'is_featured' => false,
                'sort_order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luwi',
                'photo_url' => null,
                'years_active' => '15',
                'specialty' => 'Peralatan Dapur (Caplek Kidul)',
                'story' => 'Ibu Luwi melestarikan pembuatan cobek dan wajan tradisional.',
                'quote' => 'Setiap cobek yang selesai dibakar adalah kebanggaan kami.',
                'address' => 'Blok Caplek Kidul, Desa Sitiwinangun',
                'phone' => '083867753994',
                'is_featured' => false,
                'sort_order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muniah',
                'photo_url' => null,
                'years_active' => '20',
                'specialty' => 'Cobek Tanah (Caplek Kidul)',
                'story' => 'Ibu Muniah memproduksi cobek tanah liat tradisional yang tebal dan tahan lama.',
                'quote' => 'Ketahanan cobek adalah nomor satu.',
                'address' => 'Blok Caplek Kidul, Desa Sitiwinangun',
                'phone' => '0881022525122',
                'is_featured' => false,
                'sort_order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Citra Ningsih',
                'photo_url' => null,
                'years_active' => '8',
                'specialty' => 'Kerajinan Hias (Caplek Lor)',
                'story' => 'Mbak Citra adalah pengrajin muda di Caplek Lor yang menekuni pembuatan kerajinan dekoratif.',
                'quote' => 'Semangat muda untuk melestarikan gerabah tanah air.',
                'address' => 'Blok Caplek Lor, Desa Sitiwinangun',
                'phone' => '081324009996',
                'is_featured' => false,
                'sort_order' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maeni',
                'photo_url' => null,
                'years_active' => '25',
                'specialty' => 'Peralatan Tradisional (Caplek Lor)',
                'story' => 'Ibu Maeni memproduksi aneka perkakas rumah tangga tradisional.',
                'quote' => 'Tanah liat mengajarkan kita kesabaran.',
                'address' => 'Blok Caplek Lor, Desa Sitiwinangun',
                'phone' => '081324009996',
                'is_featured' => false,
                'sort_order' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Atmi',
                'photo_url' => null,
                'years_active' => '20',
                'specialty' => 'Kendi & Pot (Caplek Lor)',
                'story' => 'Ibu Atmi aktif membuat kendi dan pot tanaman di Caplek Lor.',
                'quote' => 'Menciptakan ruang hijau yang indah lewat pot tanah liat.',
                'address' => 'Blok Caplek Lor, Desa Sitiwinangun',
                'phone' => '081324009996',
                'is_featured' => false,
                'sort_order' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sariman',
                'photo_url' => null,
                'years_active' => '35',
                'specialty' => 'Kendi & Guci Besar (Gerabah Sitiwinangun)',
                'story' => 'Pak Sariman adalah salah satu maestro gerabah Sitiwinangun yang mahir membuat guci berukuran besar.',
                'quote' => 'Karya besar membutuhkan kesabaran yang besar pula.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '081222129009',
                'is_featured' => true,
                'sort_order' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rumsani',
                'photo_url' => null,
                'years_active' => '28',
                'specialty' => 'Cobek & Coet (Coet Sani)',
                'story' => 'Ibu Rumsani adalah pemilik Coet Sani yang memproduksi cobek tanah liat dalam jumlah besar.',
                'quote' => 'Cobek tradisional buatan tangan selalu punya tempat di hati ibu rumah tangga.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '083840751249',
                'is_featured' => true,
                'sort_order' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Casmi',
                'photo_url' => null,
                'years_active' => '30',
                'specialty' => 'Celengan & Kendi (Gerabah Casmi)',
                'story' => 'Ibu Casmi memproduksi kendi air tradisional dan celengan hias.',
                'quote' => 'Tanah liat menyatukan kita dengan warisan masa lalu.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '081324009996',
                'is_featured' => false,
                'sort_order' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Murini',
                'photo_url' => null,
                'years_active' => '20',
                'specialty' => 'Vas & Wadah Air (Gerabah Murini)',
                'story' => 'Ibu Murini memproduksi vas hias dan teko air dari tanah liat.',
                'quote' => 'Membuat wadah yang menampung kesejukan.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '083126018859',
                'is_featured' => false,
                'sort_order' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suratmi',
                'photo_url' => null,
                'years_active' => '22',
                'specialty' => 'Cobek & Wajan (Gerabah Suratmi)',
                'story' => 'Ibu Suratmi memproduksi cobek tradisional dan wajan tanah liat.',
                'quote' => 'Setiap cetakan dibuat dengan ketelitian penuh.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '083813774895',
                'is_featured' => false,
                'sort_order' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Raeci',
                'photo_url' => null,
                'years_active' => '32',
                'specialty' => 'Peralatan Masak',
                'story' => 'Ibu Raeci adalah salah satu pengrajin tertua yang konsisten membuat perlengkapan masak tanah liat.',
                'quote' => 'Selama bumi menyediakan tanahnya, kita akan terus berkarya.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '081324009996',
                'is_featured' => false,
                'sort_order' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Saeni',
                'photo_url' => null,
                'years_active' => '18',
                'specialty' => 'Pot & Vas (Gerabah Saeni)',
                'story' => 'Ibu Saeni membuat vas dekorasi bergaya tradisional.',
                'quote' => 'Gerabah adalah seni yang fungsional.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '081324009996',
                'is_featured' => false,
                'sort_order' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tuimah',
                'photo_url' => null,
                'years_active' => '25',
                'specialty' => 'Celengan Hias (Gerabah Tuimah)',
                'story' => 'Ibu Tuimah membuat celengan gerabah tradisional beraneka bentuk.',
                'quote' => 'Mencetak kegembiraan di setiap celengan.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '083847082946',
                'is_featured' => false,
                'sort_order' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yuwati',
                'photo_url' => null,
                'years_active' => '20',
                'specialty' => 'Kendi Air (Gerabah Yuwati)',
                'story' => 'Ibu Yuwati konsisten memproduksi kendi air dingin tradisional.',
                'quote' => 'Menjaga air tetap sejuk dari wadah bumi.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '083141677524',
                'is_featured' => false,
                'sort_order' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Astiri',
                'photo_url' => null,
                'years_active' => '27',
                'specialty' => 'Peralatan Tradisional (Gerabah Kurmini)',
                'story' => 'Ibu Astiri mengelola bengkel Gerabah Kurmini.',
                'quote' => 'Mengalirkan keindahan tradisional ke rumah modern.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '0895400110095',
                'is_featured' => false,
                'sort_order' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suyandi',
                'photo_url' => null,
                'years_active' => '15',
                'specialty' => 'Kriya Modern (IyandiPoetery)',
                'story' => 'Pak Suyandi mendirikan IyandiPoetery, memadukan gerabah tradisional dengan teknik glasir modern.',
                'quote' => 'Setiap kreasi gerabah adalah perpaduan jiwa dan bumi.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '083878865925',
                'is_featured' => true,
                'sort_order' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yunita',
                'photo_url' => null,
                'years_active' => '10',
                'specialty' => 'Souvenir Hias (Gerabah Yunita)',
                'story' => 'Mbak Yunita adalah pengrajin muda yang fokus pada souvenir pernikahan khas gerabah.',
                'quote' => 'Memberi makna pada setiap cinderamata kecil.',
                'address' => 'Desa Sitiwinangun',
                'phone' => '0895411784429',
                'is_featured' => false,
                'sort_order' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($artisans as $artisan) {
            $id = DB::table('artisans')->insertGetId($artisan);
            $artisanIds[$artisan['name']] = $id;
        }

        // Insert Collections (Mapped to Real Artisans)
        $collections = [
            [
                'name' => 'Kendi Pratala Sitiwinangun',
                'slug' => 'kendi-pratala-sitiwinangun',
                'category_id' => $categories['kendi-wadah-air'] ?? 1,
                'photo_url' => '',
                'description' => 'Kendi air tradisional dengan hiasan relief bermotif parang tanah liat asli.',
                'history_origin' => 'Kendi ini digunakan oleh masyarakat Cirebon sejak zaman Kesultanan untuk menyimpan air minum harian agar tetap sejuk.',
                'philosophy' => 'Pratala berarti bumi, melambangkan kesuburan dan kerendahan hati.',
                'technique' => 'Teknik putar tangan (throwing) dikombinasikan dengan ukir manual.',
                'materials' => 'Tanah liat lokal Sitiwinangun, sekam padi untuk pembakaran.',
                'artisan_id' => $artisanIds['Nuradi'] ?? 1,
                'location' => 'Bengkel Gerabah Nuradi, Blok Pejaten',
                'year' => 2024,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guci Naga Sogan',
                'slug' => 'guci-naga-sogan',
                'category_id' => $categories['guci-gentong'] ?? 2,
                'photo_url' => '',
                'description' => 'Guci besar dekoratif dengan ornamen naga khas Cirebon dan pewarnaan sogan alami.',
                'history_origin' => 'Terinspirasi dari perpaduan budaya Tionghoa dan Jawa di pelabuhan kuno Cirebon.',
                'philosophy' => 'Naga melambangkan perlindungan dan kemakmuran.',
                'technique' => 'Pilin (coiling) tangan manual selama 2 minggu.',
                'materials' => 'Tanah liat merah, pewarna oksida besi alami.',
                'artisan_id' => $artisanIds['Sariman'] ?? 1,
                'location' => 'Rumah Produksi Sariman, Desa Sitiwinangun',
                'year' => 2023,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cobek Bumi Warni',
                'slug' => 'cobek-bumi-warni',
                'category_id' => $categories['peralatan-dapur'] ?? 6,
                'photo_url' => '',
                'description' => 'Cobek tradisional dengan ketahanan tinggi untuk kebutuhan dapur harian.',
                'history_origin' => 'Merupakan alat masa utama di dapur tradisional Cirebon sejak abad ke-17.',
                'philosophy' => 'Melambangkan kebersamaan dan kerja keras dalam menyiapkan pangan keluarga.',
                'technique' => 'Pinching (pijat tekan) dan cetak press.',
                'materials' => 'Tanah liat hitam vulkanis, pembakaran suhu tinggi.',
                'artisan_id' => $artisanIds['Rumsani'] ?? 1,
                'location' => 'Bengkel Coet Sani, Desa Sitiwinangun',
                'year' => 2025,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vas Anila Modern',
                'slug' => 'vas-anila-modern',
                'category_id' => $categories['vas-pot'] ?? 4,
                'photo_url' => '',
                'description' => 'Vas bunga minimalis modern dengan sentuhan tekstur kasar alami tanah liat.',
                'history_origin' => 'Desain kontemporer yang dibuat pertama kali pada pameran kerajinan nasional 2024.',
                'philosophy' => 'Anila berarti angin, membawa kesegaran baru pada desain gerabah.',
                'technique' => 'Teknik putar cepat dilanjutkan dengan carving motif garis vertikal.',
                'materials' => 'Tanah liat campuran pasir halus.',
                'artisan_id' => $artisanIds['Suyandi'] ?? 1,
                'location' => 'Studio IyandiPoetery, Desa Sitiwinangun',
                'year' => 2026,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('collections')->insert($collections);
    }
}
